package pav_sorokin;

public class App {
    public static void main(String[] args) {
        System.out.println("1.Объект – телефон");
        System.out.println("Состояние:");
        System.out.println("Включен");
        System.out.println("Выключен");
        System.out.println("Сломан");
        System.out.println("Исправен");
        System.out.println("Поведение:");
        System.out.println("Звонит");
        System.out.println("Заряжается");
        System.out.println("2.Объект – карандаш");
        System.out.println("Состояние:");
        System.out.println("Тупой");
        System.out.println("Острый");
        System.out.println("Поведение:");
        System.out.println("Писать (при использовании этого объекта он затупляется)");
        System.out.println("Точить");
        System.out.println("3.Объект – лист бумаги");
        System.out.println("Состояние:");
        System.out.println("Чистый");
        System.out.println("Исписанный");
        System.out.println("Изрисованный");
        System.out.println("Ровный");
        System.out.println("Скомканный");
        System.out.println("Поведение:");
        System.out.println("Хранит написанное");
        System.out.println("Мнется");
        System.out.println("4.Объект – диван");
        System.out.println("Состояние:");
        System.out.println("Мягкий");
        System.out.println("Обшитый тканью");
        System.out.println("Удобный");
        System.out.println("Складной");
        System.out.println("Поведение:");
        System.out.println("Складывается");
        System.out.println("Раскладывается");
        System.out.println("5.Объект – степлер");
        System.out.println("Состояние:");
        System.out.println("Заправлен скобами");
        System.out.println("Пустой");
        System.out.println("Поведение:");
        System.out.println("Сшивает листы бумаги (при сшивании расходует скобы)");
        System.out.println("6.Объект – наушники");
        System.out.println("Состояние:");
        System.out.println("Тип подключения (проводные/беспроводные)");
        System.out.println("Спутаны");
        System.out.println("Распутаны");
        System.out.println("Поведение:");
        System.out.println("Подключены");
        System.out.println("Не подключены");
        System.out.println("Проигрывают музыку");
        System.out.println("7.Объект – окно");
        System.out.println("Состояние:");
        System.out.println("Закрыто");
        System.out.println("Открыто");
        System.out.println("Чистое");
        System.out.println("Грязное");
        System.out.println("Поведение:");
        System.out.println("Помыть");
        System.out.println("Открыть");
        System.out.println("Закрыть");
        System.out.println("Разбить");
        System.out.println("8.Объект – принтер");
        System.out.println("Состояние:");
        System.out.println("Включен");
        System.out.println("Выключен");
        System.out.println("Загружен бумагой");
        System.out.println("Заправлен чернилами");
        System.out.println("Поведение:");
        System.out.println("Включить");
        System.out.println("Выключить");
        System.out.println("Печатает (при использовании этого действия количество чернил и бумаги уменьшается)");
        System.out.println("Шумит (во время печати издает шум)");
        System.out.println("9.Объект – майка");
        System.out.println("Состояние:");
        System.out.println("Новая");
        System.out.println("Старая");
        System.out.println("Чистая");
        System.out.println("Грязная");
        System.out.println("Поведение:");
        System.out.println("Стирать (при использовании этого действия майка становится чистой)");
        System.out.println("Одета на человека");
        System.out.println("Лежит в шкафу");
        System.out.println("10.Объект – радиатор отопления");
        System.out.println("Состояние:");
        System.out.println("Включен");
        System.out.println("Горячий");
        System.out.println("Холодный");
        System.out.println("Поведение:");
        System.out.println("Включить (при использовании этого действия температура радиатора увеличивается)");
        System.out.println("Выключить (при использовании этого действия температура радиатора уменьшается)");
        System.out.println("Греет помещение");

    }
}
